### ISSUE TITLE
Group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by ndikumanaisaie** [bobb-Rob/watch-movie-tv-show-app#21]
## In this issue we assigned each other tasks.

- [link to the repos](https://github.com/bobb-Rob/watch-movie-tv-show-app)
- In our team, we are two students @ndikumanaisaie @bobb-Rob

**Comment by ShadyShawkat** [comment]
## Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Image](https://media.giphy.com/media/qlrBlSDevEdFeW5JwV/giphy.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
